fancybox: true ## If you want to use fancybox please set the value to true
duoshuo: ## Your duoshuo_shortname, e.g. haomwei
disqus: zhesongblog
google_search: true ## Use Google search, true/false
baidu_search: ## Use Baidu search, true/false
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
google_analytics: UA-71845761-1
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000

menu:
  - page: home
    directory: /
    icon: icon-home
  - page: archive
    directory: archives/
    icon: icon-archive
  - page: about
    directory: about/
    icon: icon-about
  - page: guestbook
    directory: guestbook/
    icon: icon-guestbook
  - page: rss
    directory: atom.xml
    icon: icon-rss

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - search
  - category
  - tag
  - recent_posts
  - recent_comments
  - links

links:
  - title: 程序员博客墙 | Blog Wall
    url: http://www.blogwall.us/
  - title: 我的写作计划 | Writing Plan
    url: https://github.com/handsdirty/handsdirty.github.io/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc
